export const GET_COUNTRIES_BEGIN = "GET_COUNTRIES_BEGIN";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_FAILURE = "GET_COUNTRIES_FAILURE";

export const SELECT_COUNTRY = "SELECT_COUNTRY";
export const GET_COUNTRY_DATA_SUCCESS = "GET_COUNTRY_DATA_SUCCESS";
export const GET_COUNTRY_DATA_FAILURE = "GET_COUNTRY_DATA_FAILURE";

export const GET_SUMMARY_BEGIN = "GET_SUMMARY_BEGIN";
export const GET_SUMMARY_DATA_SUCCESS = "GET_SUMMARY_DATA_SUCCESS";
export const GET_SUMMARY_DATA_FAILURE = "GET_SUMMARY_DATA_FAILURE";
